services:
  - type: web
    name: api-siscob
    env: node
    plan: free
    rootDirectory: api # ESSA LINHA É CRÍTICA PARA MONOREPOS
    buildCommand: "npm install --production=false && npm run build && npm run migrate"
    startCommand: "npm start" # Agora este comando será executado DENTRO do diretório 'api/'
    healthCheckPath: /api/diag
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET
        sync: false
      - key: ALLOW_SCHEMA_RESET
        value: false
      - key: DATABASE_URL
        sync: false
